# Generated by Django 4.2.3 on 2025-03-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='compro',
            field=models.CharField(max_length=25, null=True, verbose_name='Persona que compró'),
        ),
    ]
