# Generated by Django 4.2.3 on 2025-03-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_compro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.comercio', verbose_name='Comercio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'deuda',
                'verbose_name_plural': 'deudas',
                'db_table': 'deuda',
                'ordering': ['year', 'mes', 'empleado'],
            },
        ),
    ]
