# Generated by Django 4.2.3 on 2025-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_deuda_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='correoAutorizado',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Correo Electrónico Autorizado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correoAutorizado2',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Correo Electrónico Autorizado'),
        ),
    ]
